### ISSUE TITLE
 Error creating bean with name 'messageConverters' while running the application 

### ISSUE THREAD

**Issue by deepres** [spring-guides/gs-consuming-web-service#13]
Hi,

so my previous attempt to solve this problem failed, thus I clonned the git repository, followed  the guide and builded sources in the 'complete' directory with no error, but when I did:

```
 ~/Projects/gs-consuming-web-service/complete (master)
$ java -jar build/libs/complete.jar

..
..

2015-10-23 09:23:49.865  WARN 14104 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageConverters' defined in class path resource [org/springframework/boot/autoconfigure/web/HttpMessageConvertersAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.web.HttpMessageConverters]: Factory method 'messageConverters' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/http/converter/xml/MappingJackson2XmlHttpMessageConverter
```

**Comment by dsyer** [comment]
The Maven build works for me. I don't know how to fix the Gradle build (same problem).

**Comment by deepres** [comment]
It looks like there are unsatisfied dependencies here:
compile("org.springframework.boot:spring-boot-starter")

there is no jackson lib

with this change : 
compile("org.springframework.boot:spring-boot-starter-web")

I can get further:

2015-10-23 13:43:02.786  INFO 10504 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-10-23 13:43:02.840  INFO 10504 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2015-10-23 13:43:02.841  INFO 10504 --- [           main] hello.WeatherClient                      : Requesting forecast for 94304

Ending up with the Connection refused error, but this could be the case of corporate proxy:

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:677)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:969)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:958)
        at hello.Application.main(Application.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.ws.client.WebServiceIOException: I/O error: Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:561)
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390)
        at hello.WeatherClient.getCityForecastByZIPResponse(WeatherClient.java:26)
        at hello.Application.lambda$lookup$0(Application.java:31)
        at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:674)
        ... 11 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)

**Comment by dsyer** [comment]
Jackson is not necessary to get this project working (it's all XML after all), so that change is irrelevant I think. Look at the Maven version for confirmation.

The error at the end there looks like a simple networking issue to me, so you can't connect to the service on the internet (are you behind a corporate proxy or something?).

P.S. Please use Markdown to format your comments so they are readable (in particular it is useful to put fences (```) around logs and source code).

**Comment by deepres** [comment]
Sorry for the styling, will do better from now on :) 

As for the dependency, I am getting the :
```
NoClassDefFoundError: org/springframework/http/converter/xml/MappingJackson2XmlHttpMessageConverter
```

 while instantiating the 

```
org/springframework/boot/autoconfigure/web/HttpMessageConvertersAutoConfiguration.class
```

So I guess springboot is doing too much here and it does not have all the dependencies to perform that actions within the spring-boot-starter

So I looked here for the possible solution:
http://nixmash.com/java/mappingjackson2xmlhttpmessageconverter-and-the-boot-web-dependency/

**Comment by dsyer** [comment]
It's a problem with the dependency management. Unfortunately Gradle doesn't work very well out of the box. If you look at the jar file created by Gradle and compare it with the one from Maven you will see that the Spring dependencies are wrong. I'll push a change in a minute that should fix it.
