### ISSUE TITLE
Documentation using with java 11

### ISSUE THREAD

**Issue by cah-james-shingler** [spring-guides/gs-consuming-web-service#42]
It would be helpful to include information on running the Producer and Consumer using java 11.

https://spring.io/blog/2018/09/19/spring-web-services-3-0-4-2-4-3-released

**Comment by dsyer** [comment]
I run the smoke test `text/run.sh` with Java 11 and it worked for me (there were some updates recently, maybe that helped). Did you have to do something else special?

**Comment by sniget** [comment]
This consumer example server doesn't run properly under Java 11. When running it under gradle (which also needs a note about including the glassfish runtime) and maven the server doesn't last past boot and produces the following:

```
2020-01-08 16:47:14.406  INFO 8381 --- [           main] c.e.consumingwebservice.CountryClient    : Requesting location for Spain
2020-01-08 16:47:14.412 DEBUG 8381 --- [           main] o.s.ws.client.core.WebServiceTemplate    : Opening [org.springframework.ws.transport.http.HttpUrlConnection@cb0f763] to [http://localhost:8080/ws/countries]
2020-01-08 16:47:14.444 DEBUG 8381 --- [           main] o.s.ws.client.MessageTracing.sent        : Sent request [SaajSoapMessage {http://spring.io/guides/gs-producing-web-service}getCountryRequest]
2020-01-08 16:47:14.511 DEBUG 8381 --- [           main] o.s.ws.client.MessageTracing.received    : Received response [SaajSoapMessage {http://schemas.xmlsoap.org/soap/envelope/}Fault] for request [SaajSoapMessage {http://spring.io/guides/gs-producing-web-service}getCountryRequest]
2020-01-08 16:47:14.512 DEBUG 8381 --- [           main] o.s.ws.client.core.WebServiceTemplate    : Received Fault message for request [SaajSoapMessage {http://spring.io/guides/gs-producing-web-service}getCountryRequest]
2020-01-08 16:47:14.514  INFO 8381 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-08 16:47:14.518 ERROR 8381 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at com.example.consumingwebservice.ConsumingWebServiceApplication.main(ConsumingWebServiceApplication.java:15) ~[classes/:na]
Caused by: org.springframework.ws.soap.client.SoapFaultClientException: Implementation of JAXB-API has not been found on module path or classpath.
	at org.springframework.ws.soap.client.core.SoapFaultMessageResolver.resolveFault(SoapFaultMessageResolver.java:38) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.handleFault(WebServiceTemplate.java:830) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:624) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390) ~[spring-ws-core-3.0.7.RELEASE.jar:na]
	at com.example.consumingwebservice.CountryClient.getCountry(CountryClient.java:25) ~[classes/:na]
	at com.example.consumingwebservice.ConsumingWebServiceApplication.lambda$lookup$0(ConsumingWebServiceApplication.java:26) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	... 5 common frames omitted
```

I did also have the producer service running.

**Comment by dsyer** [comment]
It looks to me like someone updated the Maven build and not the Gradle one to work with Java 11. I'm not even sure how to do that. Can anyone with some Gradle knowledge help?

**Comment by sniget** [comment]
Moved server crash to separate ticket. Smoke test passes just fine, but the server itself doesn't run.
