### ISSUE TITLE
Sample built with Gradle doesn't run with "java -jar" on Java 11

### ISSUE THREAD

**Issue by molgun** [spring-guides/gs-consuming-web-service#46]
Hello 

My JDK 

```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191016_371 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```
Exception

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        at com.example.consumingwebservice.ConsumingWebServiceApplication.main(ConsumingWebServiceApplication.java:15) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[gs-consuming-web-service-0.0.1.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[gs-consuming-web-service-0.0.1.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[gs-consuming-web-service-0.0.1.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[gs-consuming-web-service-0.0.1.jar:na]
Caused by: org.springframework.oxm.UncategorizedMappingException: Unknown JAXB exception; nested exception is javax.xml.bind.JAXBException: class com.example.consumingwebservice.wsdl.GetCountryRequest nor any of its super class is known to this context.
        at org.springframework.oxm.jaxb.Jaxb2Marshaller.convertJaxbException(Jaxb2Marshaller.java:955) ~[spring-oxm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.oxm.jaxb.Jaxb2Marshaller.marshal(Jaxb2Marshaller.java:713) ~[spring-oxm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        at org.springframework.ws.support.MarshallingUtils.marshal(MarshallingUtils.java:81) ~[spring-ws-core-3.0.7.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate$2.doWithMessage(WebServiceTemplate.java:399) ~[spring-ws-core-3.0.7.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:590) ~[spring-ws-core-3.0.7.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555) ~[spring-ws-core-3.0.7.RELEASE.jar!/:na]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390) ~[spring-ws-core-3.0.7.RELEASE.jar!/:na]
        at com.example.consumingwebservice.CountryClient.getCountry(CountryClient.java:25) ~[classes!/:na]
        at com.example.consumingwebservice.ConsumingWebServiceApplication.lambda$lookup$0(ConsumingWebServiceApplication.java:26) ~[classes!/:na]
        at com.example.consumingwebservice.ConsumingWebServiceApplication$$Lambda$287.0000000000000000.run(Unknown Source) ~[na:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
        ... 13 common frames omitted
Caused by: javax.xml.bind.JAXBException: class com.example.consumingwebservice.wsdl.GetCountryRequest nor any of its super class is known to this context.
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getBeanInfo(JAXBContextImpl.java:563) ~[jaxb-runtime-2.3.2.jar!/:2.3.2]
        at com.sun.xml.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:452) ~[jaxb-runtime-2.3.2.jar!/:2.3.2]
        at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:298) ~[jaxb-runtime-2.3.2.jar!/:2.3.2]
        at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:226) ~[jaxb-runtime-2.3.2.jar!/:2.3.2]
        at org.springframework.oxm.jaxb.Jaxb2Marshaller.marshal(Jaxb2Marshaller.java:709) ~[spring-oxm-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
        ... 22 common frames omitted
```

**Comment by dsyer** [comment]
Works for me. Did you run the service from the "producing" guide as a separate process?

**Comment by molgun** [comment]
Hi Dave,

Yes I ran the service. I build it with gradle btw.

**Comment by dsyer** [comment]
There's a bug in the jar - the generated JAXB classes are included in the root by mistake (as well as in BOOT-INF/classes where they are needed). I'm not sure how to fix that. Any Gradlers out there?

**Comment by molgun** [comment]
Hi Dave,

I think problem is bigger than this. I created a project with gradle then I followed this guide to consume a SOAP service. When I run it with ./gradlew bootRun everything works perfect. But if I build it with gradle and run it with "java -jar" Spring throws another exception. The problem is that I don't know where to post this issue :)

**Comment by dsyer** [comment]
I'm not sure why that means the "problem is bigger than this". The jar file is invalid. Let's see if someone can fix it, then we can decide.

**Comment by wilkinsona** [comment]
`from genJaxb.classesDir` is adding the classes to the root of the jar. It is redundant and can be removed.

**Comment by molgun** [comment]
Thanks Andy!!
