### ISSUE TITLE
JAXB-API error when running with gradle bootRun 

### ISSUE THREAD

**Issue by huima** [spring-guides/gs-consuming-web-service#56]
I just tested with the example code from the repository with Zulu JDK 11.

In the complete directory build goes fine, but bootRun causes following error:

`java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.1.jar:2.7.1]
        at com.example.consumingwebservice.ConsumingWebServiceApplication.main(ConsumingWebServiceApplication.java:15) ~[main/:na]
Caused by: org.springframework.ws.soap.client.SoapFaultClientException: Implementation of JAXB-API has not been found on module path or classpath.
        at org.springframework.ws.soap.client.core.SoapFaultMessageResolver.resolveFault(SoapFaultMessageResolver.java:38) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.handleFault(WebServiceTemplate.java:795) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:605) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:542) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:394) ~[spring-ws-core-3.1.3.jar:na]
        at com.example.consumingwebservice.CountryClient.getCountry(CountryClient.java:25) ~[main/:na]
        at com.example.consumingwebservice.ConsumingWebServiceApplication.lambda$lookup$0(ConsumingWebServiceApplication.java:26) ~[main/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.1.jar:2.7.1]
        ... 5 common frames omitted
`

I tested both gradle bootRun and mvn spring-boot:run

**Comment by huima** [comment]
I assume that these examples are sort of abandoned and being updated to Spring Boot 3 some time soon, as all the dependencies change towards Jakarta 9+.

I tried to double check if the project works on older JVMs on OS X, but I seem to be unable to get it to work.

When starting with Amazon Corretto JDK 8:

`
Starting process 'command '/Users/heimo.laukkanen/.sdkman/candidates/java/8.0.352-amzn/bin/java''. Working directory: /Users/heimo.laukkanen/projects/spring-sources/gs-consuming-web-service/complete Command: /Users/heimo.laukkanen/.sdkman/candidates/java/8.0.352-amzn/bin/java -Xverify:none -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8 -Duser.country=FI -Duser.language=en -Duser.variant -cp /Users/heimo.laukkanen/projects/spring-sources/gs-consuming-web-service/complete/build/classes/java/main:/Users/heimo.laukkanen/projects/spring-sources/gs-consuming-web-service/complete/build/resources/main:/Users/heimo.laukkanen/projects/spring-sources/gs-consuming-web-service/complete/build/classes/jaxb:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework.ws/spring-ws-core/3.1.3/e7d122371c5990ce547de8f412f427dee67a5120/spring-ws-core-3.1.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/jaxb-runtime/2.3.6/1e6cd0e5d9f9919c8c8824fb4d310b09a978a60e/jaxb-runtime-2.3.6.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.sun.xml.messaging.saaj/saaj-impl/1.5.3/1cd4aa51ea7a8987fe930083e3cd05e2ac72505b/saaj-impl-1.5.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/jakarta.xml.ws/jakarta.xml.ws-api/2.3.3/529fe0136be92861e5a255fbc99146f1943c4332/jakarta.xml.ws-api-2.3.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-oxm/5.3.21/a8dc2dd0235bebcc003bed55fad962cbb1d91717/spring-oxm-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework.ws/spring-xml/3.1.3/1900dc6c2ebde38ad3bc4fd4f103715719d49ae2/spring-xml-3.1.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/5.3.21/a62db425cc29c48e138846e706ca37acb138ca13/spring-webmvc-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/2.7.1/923ad789b004e8cc17d67853b1e4d3db11946f0/spring-boot-autoconfigure-2.7.1.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/2.7.1/8e49b8e7e9ea470a7772f489532264732ab206a2/spring-boot-2.7.1.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/5.3.21/fe371c85f02b8c6690fc3b3d0950ef4f965db0cd/spring-context-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-aop/5.3.21/58ec4ff7a0ce30a1e2612f04ad0fb13ea806705/spring-aop-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-web/5.3.21/317aadd37f70ba34ff93d068343e3110b5dcf2f/spring-web-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-beans/5.3.21/e3eae7e6d211381642a0b7507a5215e3ac1b32e1/spring-beans-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-expression/5.3.21/ca8c5822fc528066ec717f1e74160a1575c43192/spring-expression-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.3.21/1b0c9be6b972e4c615f175c70fc32e80557e68e8/spring-core-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/jakarta.xml.bind/jakarta.xml.bind-api/2.3.3/48e3b9cfc10752fba3521d6511f4165bea951801/jakarta.xml.bind-api-2.3.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.glassfish.jaxb/txw2/2.3.6/45db7b69a8f1ec2c21eb7d4fc0ee729f53c1addc/txw2-2.3.6.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.sun.istack/istack-commons-runtime/3.0.12/cbbe1a62b0cc6c85972e99d52aaee350153dc530/istack-commons-runtime-3.0.12.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.sun.activation/jakarta.activation/1.2.2/74548703f9851017ce2f556066659438019e7eb5/jakarta.activation-1.2.2.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/jakarta.xml.soap/jakarta.xml.soap-api/1.4.2/4f71fa8ca30be4d04ba658339df3c927fa21209a/jakarta.xml.soap-api-1.4.2.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.jvnet.staxex/stax-ex/1.8.3/4d69b68ee007aa15238cd4477392068b32747df3/stax-ex-1.8.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/jakarta.jws/jakarta.jws-api/2.1.0/7d283ef13e49c1422701e30639371edca788c609/jakarta.jws-api-2.1.0.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.springframework/spring-jcl/5.3.21/b41a2888c0e708f9fd12cf9cc0c29cebbcab2e5e/spring-jcl-5.3.21.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/jakarta.annotation/jakarta.annotation-api/1.3.5/59eb84ee0d616332ff44aba065f3888cf002cd2d/jakarta.annotation-api-1.3.5.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.30/8fde7fe2586328ac3c68db92045e1c8759125000/snakeyaml-1.30.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.13.3/ad2f4c61aeb9e2a8bb5e4a3ed782cfddec52d972/jackson-datatype-jsr310-2.13.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-parameter-names/2.13.3/f71c4ecc1a403787c963f68bc619b78ce1d2687b/jackson-module-parameter-names-2.13.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.13.3/7198b3aac15285a49e218e08441c5f70af00fc51/jackson-annotations-2.13.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.13.3/a27014716e4421684416e5fa83d896ddb87002da/jackson-core-2.13.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.13.3/d4884595d5aab5babdb00ddbd693b8fd36b5ec3c/jackson-datatype-jdk8-2.13.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.13.3/56deb9ea2c93a7a556b3afbedd616d342963464e/jackson-databind-2.13.3.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.11/4741689214e9d1e8408b206506cbe76d1c6a7d60/logback-classic-1.2.11.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-to-slf4j/2.17.2/17dd0fae2747d9a28c67bc9534108823d2376b46/log4j-to-slf4j-2.17.2.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/1.7.36/ed46d81cef9c412a88caef405b58f93a678ff2ca/jul-to-slf4j-1.7.36.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.2.11/a01230df5ca5c34540cdaa3ad5efb012f1f1f792/logback-core-1.2.11.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.36/6c62681a2f655b49963a5983b8b0950a6120ae14/slf4j-api-1.7.36.jar:/Users/heimo.laukkanen/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.17.2/f42d6afa111b4dec5d2aea0fe2197240749a4ea6/log4j-api-2.17.2.jar com.example.consumingwebservice.ConsumingWebServiceApplication
Successfully started process 'command '/Users/heimo.laukkanen/.sdkman/candidates/java/8.0.352-amzn/bin/java''
`
I still end up with the same errors as with newer JDK.

`
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-11-22 10:01:23.415 ERROR 75688 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) [spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) [spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.7.1.jar:2.7.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) [spring-boot-2.7.1.jar:2.7.1]
        at com.example.consumingwebservice.ConsumingWebServiceApplication.main(ConsumingWebServiceApplication.java:15) [main/:na]
Caused by: org.springframework.ws.soap.client.SoapFaultClientException: Implementation of JAXB-API has not been found on module path or classpath.
        at org.springframework.ws.soap.client.core.SoapFaultMessageResolver.resolveFault(SoapFaultMessageResolver.java:38) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.handleFault(WebServiceTemplate.java:795) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:605) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:542) ~[spring-ws-core-3.1.3.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:394) ~[spring-ws-core-3.1.3.jar:na]
        at com.example.consumingwebservice.CountryClient.getCountry(CountryClient.java:25) ~[main/:na]
        at com.example.consumingwebservice.ConsumingWebServiceApplication.lambda$lookup$0(ConsumingWebServiceApplication.java:26) [main/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.1.jar:2.7.1]
        ... 5 common frames omitted
`

**Comment by huima** [comment]
Found out the problem, will create pull request.

**Comment by huima** [comment]
https://github.com/spring-guides/gs-producing-web-service/pull/41
